### ISSUE TITLE
Add Functionality to the Get started button

### ISSUE THREAD

**Issue by SnehansuBehera** [TailoredUI/TailoredUI#17]
### Description

Get Started button does not lead to any where, functionality and routing should be added to the button all over the web page.

**Comment by SnehansuBehera** [comment]
I am a contributor at GSSoC'24.
I want contribute to it and I will be active with this project , please assign me this issue.

**Comment by chandel-aman** [comment]
@SnehansuBehera Please follow the template that has been provided.
Also you have not mentioned the approach/solution that you will be taking.

**Comment by chandel-aman** [comment]
Closing the issue for not following the guidelines and missing approach.

**Comment by chandel-aman** [comment]
Make a new issue with an apt solution.
