### ISSUE TITLE
Adding footer features to the site

### ISSUE THREAD

**Issue by surendar-05** [TailoredUI/TailoredUI#18]
### Description
Creating a footer section for a blogging website involves designing a space that complements the overall aesthetics of your site while providing useful information and navigation options for your visitors.

**Comment by SnehansuBehera** [comment]
I am a contributor at GSSoC'24.
I want contribute to it and I will be active with this project , please assign me this issue.

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by sarthak-stranger** [comment]
Hi, Can you please assign this issue to me, i have so experience in designing, and there is no social links in footer section and it is not looking good, I will add some social
![Screenshot (209)](https://github.com/TailoredUI/TailoredUI/assets/92575432/e6ca847f-b5bd-48c4-aab4-9859a836a878)
 links and also improve UI.

**Comment by AlaynaShaheen** [comment]
Hello Surender,

I am a a contributor participating in GSSoC'24. I want to add social links to the footer to make it visually appealing and interactive. I've good experience and I am eager to contribute to this project. Looking forward on your guidance on how to proceed.

Regards,
Alayna Shaheen

**Comment by git-akhi3** [comment]
Hey I am a frontend developer, with expertise in react 
Please assign me this task

**Comment by IP80808080** [comment]
Sir please assign this issue to me. Also Sir can you plz label it for level

**Comment by chandel-aman** [comment]
@surendar-05 
Please follow the issue template for creating any new issue. Also you clearly mentioned what you are proposing to do.
Also if your issue is around adding/changing the existing design then please give a reference of the design that you will be making. And ask it to be reviewed first.

**Comment by chandel-aman** [comment]
Closing the issue for now.
Make a new issue following the guidelines.
You can go through the contribution guidelines here https://github.com/TailoredUI/TailoredUI/blob/main/CONTRIBUTING.md

**Comment by surendar-05** [comment]
Okay Understood!
