### ISSUE TITLE
Fix [404 not found page]

### ISSUE THREAD

**Issue by ishitaa-dhingra** [TailoredUI/TailoredUI#20]
### Screenshots
![Screenshot 2024-05-10 130209](https://github.com/TailoredUI/TailoredUI/assets/110631113/a1c0cf3c-933f-44b1-8e0d-180a9d25f599)

### Additional Information
This page could be enhanced and fixed 
Please assign me this issue under gssoc'24

**Comment by chandel-aman** [comment]
@ishitaa-dhingra Go through the contribution guidlines https://github.com/TailoredUI/TailoredUI/blob/main/CONTRIBUTING.md
1. Follow the template provided for creating the issue.
2. Mention clearly what changes/enhancement you are suggesting

**Comment by chandel-aman** [comment]
Closing the issue for not following the template and no clear implementation plan provided.
