### ISSUE TITLE
Logo in the navbar does not links to the home page

### ISSUE THREAD

**Issue by AMISH-KHAN** [TailoredUI/TailoredUI#24]
## Bug Report

The logo in the navbar does not links to the home page which is common in most of the website.

### Steps to Reproduce

1. Go to https://tailoredui.netlify.app/
2. Click on logo

### Expected Behavior

it should take you to the home page

### Actual Behavior

it does not do anything

### Screenshots

![Screenshot 2024-05-10 234829](https://github.com/TailoredUI/TailoredUI/assets/123164129/8f56df34-732a-4276-8088-0b462e4030c6)

### Additional Information
I am a contributor in GSSOC. Please assign this issue to me so that I can work on it.
[Any additional information or context that might be relevant to the issue.]

**Comment by SaranshBangar** [comment]
@chandel-aman sir, can I takeover this issue?

**Comment by AMISH-KHAN** [comment]
@chandel-aman I have made the PR #40. please review it

**Comment by Nkmeoo7** [comment]
hey  assign me also on this  i can fix this
