### ISSUE TITLE
[BUG] : Template path is not directing to path defined in navigation

### ISSUE THREAD

**Issue by richab246** [TailoredUI/TailoredUI#32]
### Description

When we click on Template in the navbar, it gives a 404 error, not directing us to the correct path.

### Steps to Reproduce

1. Go to the website's  navbar
2. Click on Template
3. It will give a 404 error

### Expected Behavior

It should redirect to the '/collections' path and will give the correct template code.

### Actual Behavior
 
It's going to the '/template' path and giving a 404 error

### Screenshots

![Screenshot 2024-05-11 114805](https://github.com/TailoredUI/TailoredUI/assets/79681567/999ec1e9-daa9-4621-970f-dda1391ba67f)

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser: [e.g., Chrome, Firefox, Safari]
- Version: [e.g., 22]

### Additional Information

I am a participant in GSSoC 2024, please assign this issue to me

**Comment by AkashSharma001** [comment]
@richab246 
It should redirect to '/template' as of now. The template page hasn't been created yet

**Comment by richab246** [comment]
@AkashSharma001  Can I create template page
