### ISSUE TITLE
Improve the readme and add a LEARN.md

### ISSUE THREAD

**Issue by MadhunishaBala** [TailoredUI/TailoredUI#37]
Adding a LEARN.md file ensures anyone viewing the project find it easier to get to know more about the project in a glance through visual aids or descriptive writing. Would you please assign this issue under me, for GSSOC"24?

**Comment by AkashSharma001** [comment]
@MadhunishaBala 
We don't think the current project status is too complex to understand. If you find it difficult, feel free to suggest changes. We'll add them to the readme file.
