### ISSUE TITLE
Clicking on the TailoredUI Icon on the navbar is doing nothing

### ISSUE THREAD

**Issue by Swathikrishna-0** [TailoredUI/TailoredUI#38]
### Description

When we click on the TailoredUI Icon on the Navbar the page should be routed to the home page. Instead it does Nothing.

### Steps to Reproduce

[Outline the steps to reproduce the behavior:]

1. Go to 'any other route on navbar'
2. Click on 'TailoredUI icon'
3. See error the icon isn't clickable and does nothing

### Expected Behavior

When we click on the Icon it should navigate to the main/home page.

### Actual Behavior

TailoredUI Icon is not clickable and not routing.

### Screenshots

https://github.com/TailoredUI/TailoredUI/assets/88281761/205a8035-d8e7-4396-84af-b1b1d09dee6c

### Environment

- Operating System: Windows 11
- Browser: Chrome
- Version: 124.0.6367.156

**Comment by Madhu-mac** [comment]
@chandel-aman Assign me this issue to me under GSSoc'24 and add lables to it,  so that i can work on it

**Comment by chandel-aman** [comment]
Closing this issue since it is duplicate.
