### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by Dhruv-Pattel** [TailoredUI/TailoredUI#39]
This repository has no Code of Conduct. any open-source project needs to set clear standards for behavior. It promotes inclusivity, prevents misconduct, fosters accountability, and maintains a positive environment.

Please assign this issue to me.

**Comment by chandel-aman** [comment]
@Dhruv-Pattel Make sure you review the points with us before working on it.

**Comment by Dhruv-Pattel** [comment]
where can I discuss the points?

> @Dhruv-Pattel Make sure you review the points with us before working on it.

**Comment by chandel-aman** [comment]
> where can I discuss the points?
> 
> > @Dhruv-Pattel Make sure you review the points with us before working on it.
> 
> 

@Dhruv-Pattel You could do it here or create a discussion.

**Comment by Dhruv-Pattel** [comment]
hey @chandel-aman ! I have made a list of points for the code of conduct. these are Our Pledge, Our Standards, Enforcement Responsibilities, Scope, Enforcement, Enforcement Guidelines, and Attribution. 
Do you have any other points you would like me to add?

**Comment by chandel-aman** [comment]
> hey @chandel-aman ! I have made a list of points for the code of conduct. these are Our Pledge, Our Standards, Enforcement Responsibilities, Scope, Enforcement, Enforcement Guidelines, and Attribution. Do you have any other points you would like me to add?

Yeah, you could add these points as well:
1. Purpose
2. Expected Behavior
3. Unacceptable Behavior
4. Consequences
5. Reporting Guidelines

Club points under enforcement, rest are good to go.
