### ISSUE TITLE
Responsive Contact Section in Footer

### ISSUE THREAD

**Issue by Ashish-Ujjwal** [TailoredUI/TailoredUI#45]
### Description

I Want to Work on Contact Section as there is no any contact section in this website.

### Proposed Solution

It enhance user engagement and improve accessibility by adding a contact section to the footer.
1. Convenience for Users
2. Increased Interaction
3. Feedback Mechanism
4. Accessibility

### Alternatives

Contact Page: Instead of placing the contact section in the footer, creating a dedicated "Contact Us" page could be an alternative. This page could include more extensive contact information, such as phone numbers, addresses, and social media links, along with a contact form. However, this approach might require users to navigate away from their current page to access the contact information.

### Some Idea of Contact Section through Image .......
Kindly assign this to me under GSSoC'24
Pls, Assign me this task ........ under GSSoC'24

![Screenshot 2024-05-11 152150](https://github.com/TailoredUI/TailoredUI/assets/144592700/d2fc4a05-14bf-448d-a79d-38638c56f49c)

**Comment by AkashSharma001** [comment]
@Ashish-Ujjwal 
We don't need Contact section.
