### ISSUE TITLE
[Feat]: Navbar Redesign

### ISSUE THREAD

**Issue by Ratnesh-Rajput** [TailoredUI/TailoredUI#51]
## Feature Request
 Navbar Redesign
### Description

The current navbar needs to be redesigned as it looks cluttered with icons with very limited spacing between them, thus degrading the overall user exxperience.
![Screenshot 2024-05-12 024612](https://github.com/TailoredUI/TailoredUI/assets/105653121/4a1ac2c8-e037-4772-9435-cee99ea248a7)

### Proposed Solution

 I would like to reduce cluttering, add more spacing and more simplicity to the navbar (after discussion with the admins on design attributes).

### Alternatives
---X----

### Additional Information
@chandel-aman @sanjay-kv 
Please assign me this task under GSsoc'24

**Comment by chandel-aman** [comment]
@Ratnesh-Rajput I beg to differ. I don't feel the Navbar is cluttered, and sufficient spacing is available between the elements.
