### ISSUE TITLE
[Bug]: Logo on Navbar  doesn't redirect to base url

### ISSUE THREAD

**Issue by Ratnesh-Rajput** [TailoredUI/TailoredUI#52]
### Description

The logo/project icon (of TailoredUI) isn't working as ideally it should redirect the user to the homepage/base url. 

### Steps to Reproduce

[Outline the steps to reproduce the behavior:]

1. Go to 'https://tailoredui.netlify.app/'
2. Click on the SVG icon on the navbar .
3. it doesn't redirect to any location.

### Expected Behavior

Upon clicking the SVG icon/logo , the user should be redirected to the homepage or base URL.

### Screenshots

![Screenshot 2024-05-12 024555](https://github.com/TailoredUI/TailoredUI/assets/105653121/80a25426-7936-43e6-91f7-ba2d0b90439c)

### Environment

- Operating System: [ Windows, Linux]
- Browser: [e.g., Chrome, Firefox]

### Additional Information
@sanjay-kv @chandel-aman 
Please assign this issue to me under GSsoc'24 tag.

**Comment by chandel-aman** [comment]
@Ratnesh-Rajput This issue has already been raised #24.

**Comment by Ratnesh-Rajput** [comment]
Thanks for addressing the issue so quickly.
