### ISSUE TITLE
Menu button not working in mobile view

### ISSUE THREAD

**Issue by Abhi-0001** [TailoredUI/TailoredUI#60]
## Bug Report
Menu button not working 

### Description
Menu button in mobile view must show the website's tabs. But I think onClick handler is not added and  the UI for tabs box is not prepared. 

### Steps to Reproduce
1. Set up styling for the tabs box for mobile view
2. Add onClick handler on menu button.

### Expected Behavior
Tabs should be visible on clicking the menu button

### Actual Behavior

Tabs not showing on clicking the menu button

### Environment

- Operating System: Android/mobile view
- Browser: Google Chrome

**Comment by Abhi-0001** [comment]
Hello @chandel-aman I found this issue with the menu button. Can i work on it? Please assign the issue under GSSoC'24

**Comment by chandel-aman** [comment]
Closing since this is a duplicate issue.
(Non Functional Menu Icon on Mobile Screens #27 )
