### ISSUE TITLE
Enhancement: Make the Navigation Bar Sticky

### ISSUE THREAD

**Issue by PranavKeshav24** [TailoredUI/TailoredUI#66]
### Description

To facilitate better access to the navigation links, the navigation bar should be made sticky even after scrolling. Currently, it is not. This ensures that important navigation links remain easily accessible to users as they explore the content of a website.

### Proposed Solution

Making the navigation bar sticky so that the user has access to navigation links even while scrolling through the website.

### Alternatives

An alternative is to have a scroll up button at the bottom right of the screen which takes the user back to the hero section.

### Additional Information

I am a contributor in GSSOC’ 24. Please assign me this issue, I would love to work on it.

**Comment by chandel-aman** [comment]
@PranavKeshav24 As of now we don't intend on changing the design or placement of navbar.
