### ISSUE TITLE
Enhancement of search box

### ISSUE THREAD

**Issue by yugal1107** [TailoredUI/TailoredUI#73]
Search box is not looking good. After clicking on search icon all window gets blur.
On clicking search icon it should open a search box on vanbar itself with appropriate animations.

![image](https://github.com/TailoredUI/TailoredUI/assets/119532503/765ab718-bed1-4bb6-b9b0-e46ad9717154)

**Comment by yugal1107** [comment]
Please assign this issue to me under gssoc and add appropriate label.

**Comment by chandel-aman** [comment]
@yugal1107 We appreciate your suggestion, but that is how we want the search to function.
